name: flutter_playground
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-362.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.6.0
  firebase_core: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
