// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0bmIdN6iPlOyKQKTAtyzXFxKi5PhqL6Q',
    appId: '1:154132036526:web:2c77d2a272087ce234263f',
    messagingSenderId: '154132036526',
    projectId: 'flutter-playground-145',
    authDomain: 'flutter-playground-145.firebaseapp.com',
    storageBucket: 'flutter-playground-145.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq5y6DKRePuiSPOjWPFObMSpJpxDsDyWk',
    appId: '1:154132036526:android:c485aefb4117347334263f',
    messagingSenderId: '154132036526',
    projectId: 'flutter-playground-145',
    storageBucket: 'flutter-playground-145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbiEw80PYXQlnRPM36BnKrLm9pOPVsnGI',
    appId: '1:154132036526:ios:7d6f5bfc41c5097234263f',
    messagingSenderId: '154132036526',
    projectId: 'flutter-playground-145',
    storageBucket: 'flutter-playground-145.appspot.com',
    iosClientId: '154132036526-g3ch98h1hd7ls3ci8so75ms0feucp00d.apps.googleusercontent.com',
    iosBundleId: 'com.example.listenerBug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbiEw80PYXQlnRPM36BnKrLm9pOPVsnGI',
    appId: '1:154132036526:ios:a6e0eaaf60fe2ea534263f',
    messagingSenderId: '154132036526',
    projectId: 'flutter-playground-145',
    storageBucket: 'flutter-playground-145.appspot.com',
    iosClientId: '154132036526-vepsfkngukjefpjmajpfps6id7sc67dk.apps.googleusercontent.com',
    iosBundleId: 'com.example.listenerBug.RunnerTests',
  );
}
